---
title: "lab3"
author: "Eleanore Brugh"
date: "2026-03-05"
output: html_document
---
#Lab3 Exercises

```{r packages}

library(spdep)
library(tidycensus)
library(sf)
library(tidyverse)
library(tmap)
library(stringr)

```

```{r}

options(tigris_use_cache = TRUE)

```


```{r data}

d.all <- get_acs(geography = "county",
                 table = "B15003",
                 output = "wide",
                 geometry = T,
                 year = 2020)

```

```{r}

glimpse(d.all)

```

```{r download variables}

df.vars <- load_variables(2020, "acs5", cache = T)

glimpse(df.vars)

```


```{r filter data to female population aged 75-79}

df.vars %>% dplyr::filter(concept == "SEX BY AGE") %>%
  dplyr::filter(str_detect(label, "Female")) %>%
  dplyr::filter(str_detect(label, "75"))

```


```{r a lot of data}

d.sex.by.age <- get_acs(geography = "county",
                        table = "B01001",
                        output = "wide",
                        geometry = T,
                        year = 2020)

glimpse(d.sex.by.age)

```


```{r}

ohio <- d.sex.by.age %>%
  mutate(., STATEID = stringr::str_sub(GEOID, 1, 2)) %>%
  dplyr::filter(STATEID == "39") 

tmap::tm_shape(ohio) + tm_polygons()

```

```{r checking coordinate system}

sf::st_crs(ohio)

```


```{r reproject}
#north america equidistant conic
ohio.projected <- ohio %>% sf::st_transform(., "ESRI:102010")

```

```{r map it again}

tmap::tm_shape(ohio.projected) + tm_polygons()

```

```{r making the neighborhood}

nb <- spdep::poly2nb(ohio.projected, queen = TRUE)

nb

#to see the neighbors in the first polygon in the object
nb[[1]]

```


```{r counties in index 1}
##Erie County Ohio
ohio.projected$NAME[1]

##Lorain, Sandusky, and Huron the neighbors
nb[[1]] %>% ohio.projected$NAME[.]

```

```{r assigning weights to each neighboring polygon}

#zero.policy=TRUE allows for lists of non-neighbors (use with caution)
lw <- spdep::nb2listw(nb, style="W", zero.policy=TRUE)

#see the weight of the first polygons four neighbors
lw$weights[1]

```

```{r}
#using the attribute to get the count of neighbors in W
neighbors <- attr(lw$weights,"comp")$d 

#plotting it
hist(neighbors)

```

```{r}
#average neighboring F 75-79 values
F75.lag <- lag.listw(lw, ohio.projected$B01001_047E)
F75.lag

```

###Morans 
```{r}

moran.test(ohio.projected$B01001_047E, lw)

```


###Moran's Plots
```{r}

moran.plot(ohio.projected$B01001_047E, lw, zero.policy=TRUE, plot=TRUE)

```



#MY TASKS
###Task 1
```{r poverty data}

options(tigris_use_cache = TRUE)

d.poverty <- get_acs(
  geography = "county",
  table = "B17001",
  output = "wide",
  geometry = TRUE,
  year = 2020
)

glimpse(d.poverty)

```

```{r subset}

#Ohio, Indian, Kentucky, West Virginia
four_states <- d.poverty %>%
  mutate(STATEID = stringr::str_sub(GEOID, 1, 2)) %>%
  filter(STATEID %in% c("39", "18", "21", "54"))

glimpse(four_states)
```

###Task 2
```{r normalize}
#the poverty counts and total population to determine the percent of people below the poverty line for each county
four_states <- four_states %>%
  mutate(poverty_pct = (B17001_002E / B17001_001E) * 100)

```

###Task 3
```{r histogram}

hist(
  four_states$poverty_pct,
  main = "County Poverty Rate For OH,IN,KT,WV",
  xlab = "Percent Below Poverty",
  col = "darkgreen" 
)

```

###Task 4
```{r }

tm_shape(four_states) +
  tm_polygons("poverty_pct", 
              style = "quantile",
              palette = "greens") +
  tm_layout(frame = FALSE)

```


```{r four states}

#Ohio, Indian, Kentucky, West Virginia
states <- c("39", "18", "21", "54")

subs


###Task 2


###Task 3


###Task 4


###Task 5
####Task5.1


####Task5.2


####Task5.3


####Task5.4


###Task 6
####Task6.1


####Task6.2


####Task6.3


####Task6.4



#QUESTIONs
###Q1

